package com.java.example;

import java.io.IOException;

public class CustomException {

	public static void main(String[] args) {
//		try {
//			throw new Exception();
//		} catch (Exception e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} finally {
//
//		}
		int array[] = new int[] { 123, 45, 44, 8787 };
		System.out.println(array.length);
		// try
//
//		{
//			throw new Exception();
//		} finally {
//
//		}
	}

	public int add(int a, int b) throws IOException {

		return a + b;
	}
}
